/* Generated By:JJTree: Do not edit this line. ASTAbsoluteTimeLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.metrink.grammar.javacc;

public
class ASTAbsoluteTimeLiteral extends com.metrink.grammar.BaseNode {
  public ASTAbsoluteTimeLiteral(int id) {
    super(id);
  }

  public ASTAbsoluteTimeLiteral(MetrinkParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public com.metrink.grammar.ASTWalker.WalkType jjtAccept(MetrinkParserVisitor visitor, Boolean data) throws com.metrink.grammar.MetrinkParseException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a635b8b8f1fd68d99f7fde8e9ec4513c (do not edit this line) */
