/* Generated By:JJTree: Do not edit this line. ASTAbsoluteDateLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.metrink.grammar.javacc;

public
class ASTAbsoluteDateLiteral extends com.metrink.grammar.BaseNode {
  public ASTAbsoluteDateLiteral(int id) {
    super(id);
  }

  public ASTAbsoluteDateLiteral(MetrinkParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public com.metrink.grammar.ASTWalker.WalkType jjtAccept(MetrinkParserVisitor visitor, Boolean data) throws com.metrink.grammar.MetrinkParseException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9ad0392630f48e74d6cfea64b05f46d4 (do not edit this line) */
