/* Generated By:JJTree: Do not edit this line. ASTRelativeTimeIndicator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.metrink.grammar.javacc;

public
class ASTRelativeTimeIndicator extends com.metrink.grammar.BaseNode {
  public ASTRelativeTimeIndicator(int id) {
    super(id);
  }

  public ASTRelativeTimeIndicator(MetrinkParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public com.metrink.grammar.ASTWalker.WalkType jjtAccept(MetrinkParserVisitor visitor, Boolean data) throws com.metrink.grammar.MetrinkParseException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3bd73cc40e1cf2174b899c75b92b9f7d (do not edit this line) */
