/* Generated By:JavaCC: Do not edit this line. MetrinkParserTreeConstants.java Version 5.0 */
package com.metrink.grammar.javacc;

public interface MetrinkParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTALERTQUERY = 1;
  public int JJTTRIGGEREXPRESSION = 2;
  public int JJTGRAPHQUERY = 3;
  public int JJTGRAPHEXPRESSION = 4;
  public int JJTCONNECTOR = 5;
  public int JJTMETRIC = 6;
  public int JJTSTRINGARRAY = 7;
  public int JJTFUNCTION = 8;
  public int JJTFUNCTIONNAME = 9;
  public int JJTARGUMENTLIST = 10;
  public int JJTARGUMENT = 11;
  public int JJTADDITIVEEXPRESSION = 12;
  public int JJTMULTIPLICATIVEEXPRESSION = 13;
  public int JJTSTRINGLITERAL = 14;
  public int JJTNUMBERLITERAL = 15;
  public int JJTRELATIVETIMEARRAY = 16;
  public int JJTRELATIVETIMELITERAL = 17;
  public int JJTABSOLUTEDATELITERAL = 18;
  public int JJTABSOLUTETIMELITERAL = 19;
  public int JJTPERCENTLITERAL = 20;
  public int JJTBOOLEANLITERAL = 21;
  public int JJTINTEGERLITERAL = 22;
  public int JJTRELATIVETIMEINDICATOR = 23;
  public int JJTCONJUNCTION = 24;
  public int JJTCOMPARATOR = 25;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "AlertQuery",
    "TriggerExpression",
    "GraphQuery",
    "GraphExpression",
    "Connector",
    "Metric",
    "StringArray",
    "Function",
    "FunctionName",
    "ArgumentList",
    "Argument",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "StringLiteral",
    "NumberLiteral",
    "RelativeTimeArray",
    "RelativeTimeLiteral",
    "AbsoluteDateLiteral",
    "AbsoluteTimeLiteral",
    "PercentLiteral",
    "BooleanLiteral",
    "IntegerLiteral",
    "RelativeTimeIndicator",
    "Conjunction",
    "Comparator",
  };
}
/* JavaCC - OriginalChecksum=df3322af215e0604dfbc73547854f7be (do not edit this line) */
