/* Generated By:JavaCC: Do not edit this line. MetrinkParserVisitor.java Version 5.0 */
package com.metrink.grammar.javacc;

public interface MetrinkParserVisitor
{
  public com.metrink.grammar.ASTWalker.WalkType visit(SimpleNode node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTCompilationUnit node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTAlertQuery node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTTriggerExpression node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTGraphQuery node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTGraphExpression node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTConnector node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTMetric node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTStringArray node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTFunction node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTFunctionName node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTArgumentList node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTArgument node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTAdditiveExpression node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTMultiplicativeExpression node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTStringLiteral node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTNumberLiteral node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTRelativeTimeArray node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTRelativeTimeLiteral node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTAbsoluteDateLiteral node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTAbsoluteTimeLiteral node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTPercentLiteral node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTBooleanLiteral node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTIntegerLiteral node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTRelativeTimeIndicator node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTConjunction node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
  public com.metrink.grammar.ASTWalker.WalkType visit(ASTComparator node, Boolean data) throws com.metrink.grammar.MetrinkParseException;
}
/* JavaCC - OriginalChecksum=513163a04c9c8f0bae35bfd044056c02 (do not edit this line) */
