port: 8080

pid_file: metrink.pid

development: true

db:
  dialect: org.hibernate.dialect.MySQLDialect
  driver: org.gjt.mm.mysql.Driver
  jdbc_url: jdbc:mysql://localhost/metrink
  user: root
  pass: root

cassandra:
  cluster_name: Test Cluster
  keyspace: metrink

email:
  server: smtp.gmail.com
  ssl_port: 465
  user: no-reply@educatedsolutionsllc.com
  pass: 4emailsendingonly

logging:
    console:
        logFormat: "%-5level %date{ISO8601} [%X{sessionId}] [%X{user}] %c: %m%n"
    file:
        logFormat: "%-5level %date{ISO8601} [%X{sessionId}] [%X{user}] %c: %m%n"
    loggers:
        "com.metrink": DEBUG
        "com.es": DEBUG
        "org.hibernate": WARN        
        "com.sop4j": DEBUG        
        
